package com.frank142857.metropolis.world.city;

public class BuildingPatterns {
    public static final String[] BASE_1 = new String[]{
            "KKKKKKKKKKKKKKKK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KKKKKKKKKKKKKKKK",
    };

    public static final String[][] FLOORS_1 = new String[][]{
            {
                    "                ",
                    " SSSSSSSSSSSSSS ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " SSSSSSSSSSSSSS ",
                    "                "
            },
            {
                    "   HHH    HHH   ",
                    " SSSSSSSSSSSSSS ",
                    " S            S ",
                    "HS            SH",
                    "HS            SH",
                    "HS            SH",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    "HS            SH",
                    "HS            SH",
                    "HS            SH",
                    " S            S ",
                    " SSSSSSSSSSSSSS ",
                    "   HHH    HHH   "
            },
            {
                    "                ",
                    " SSGGGSSSSGGGSS ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " SSGGGSSSSGGGSS ",
                    "                "
            },
            {
                    "                ",
                    " SSGGGSSSSGGGSS ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " SSGGGSSSSGGGSS ",
                    "                "
            },
            {
                    "                ",
                    " SSGGGSSSSGGGSS ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " S     OO     S ",
                    " S     OO     S ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " SSGGGSSSSGGGSS ",
                    "                "
            },
            {
                    "                ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    "                "
            }
    };
    public static final String[][] FLOORS_2 = new String[][]{
            {
                    "                ",
                    " SSSSSSSSSSSSSS ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " SSSSSSSSSSSSSS ",
                    "                "
            },
            {
                    "                ",
                    " SSSSSSSSSSSSSS ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " SSSSSSSSSSSSSS ",
                    "                "
            },
            {
                    "                ",
                    " SSGGGSSSSGGGSS ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " SSGGGSSSSGGGSS ",
                    "                "
            },
            {
                    "                ",
                    " SSGGGSSSSGGGSS ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " SSGGGSSSSGGGSS ",
                    "                "
            },
            {
                    "                ",
                    " SSGGGSSSSGGGSS ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " S     OO     S ",
                    " S     OO     S ",
                    " S            S ",
                    " G            G ",
                    " G            G ",
                    " G            G ",
                    " S            S ",
                    " SSGGGSSSSGGGSS ",
                    "                "
            },
            {
                    "                ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    " SSSSSSSSSSSSSS ",
                    "                "
            }
    };
    public static final BuildingPattern[] FLOORS_NORMAL = new BuildingPattern[]{
            new BuildingPattern(BuildingPatternType.FLOOR, FLOORS_1),
            new BuildingPattern(BuildingPatternType.FLOOR, FLOORS_2),
    };
}